### ISSUE TITLE
Was dbConnect character method removed intentionally?

### ISSUE THREAD

**Issue by joshuaulrich** [rstats-db/RMySQL#62]
I received a bug report that [`quantmod::getSymbols.MySQL`](https://github.com/joshuaulrich/quantmod/blob/develop/R/getSymbols.R#L594) no longer works, and it looks like it's because the `RMySQL::dbConnect` character method ([used here](https://github.com/joshuaulrich/quantmod/blob/develop/R/getSymbols.R#L619)) was removed. I can't tell from [the commit message and diff](https://github.com/rstats-db/RMySQL/commit/051eeddcf6e8e0ccac9ae6bef42343241ff2b264#diff-30bde6a0d7563b50611c11cb8b94575cL12) whether or not this was intentional.  I see in the release notes that the function it would have used (`mysqlNewConnection`) was abruptly removed (please, in the future, deprecate before removing to give users a chance to adjust).

I've never used `quantmod::getSymbols.MySQL`, so I'd really appreciated some pointers on how to fix it if the RMySQL method was indeed removed intentionally.

**Comment by hadley** [comment]
Yes, I think it's a bad idea because it's difficult to scope a string to a namespace. You should just be able to switch from `dbConnect("MySQL", ...)` to `dbConnect(RMySQL::MySQL, ...)`.  

(This should allow you to just important RMySQL and so you don't have to depend on it)

**Comment by joshuaulrich** [comment]
Thanks, I'll ask the user to try that.  And RMySQL is currently a Suggests, not a Depends.

**Comment by hadley** [comment]
Ah, in that case it's slightly better to switch from `if (require("RMySQL")` to `if (requireNamespace("RMySQL", quietly = TRUE)`, if you haven't already.

**Comment by joshuaulrich** [comment]
Yeah, I've already made that switch. And it's more than "slightly better".  Calling `require` is now a NOTE when running `R CMD check --as-cran` and will likely prevent packages from being accepted.

**Comment by hadley** [comment]
It's slightly better from the users perspective ;)  (well it's probably actually slightly worse if you expected that package to be attached)

**Comment by LGTrader** [comment]
I'm not the OP on this problem but see the problem as well. I probably don't understand the above ideas correctly but modified my code (snippets)

library(RMySQL)
requireNamespace("RMySQL", quietly = TRUE)

and...

if (UseMySQL){
  if (MyAdjust) { dbName = paste0(dbName, "Adjust")}
#   dbc = dbConnect(MySQL(), dbname=dbName)
  dbc = dbConnect(RMySQL::MySQL, dbname=dbName)

#  setDefaults(getSymbols.MySQL, user="mark", password="MyTempPassword", dbname=dbName)
}

which produced a different error message, now about 'function' instead of chartacter:


 Show Traceback
 
 Rerun with Debug
 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbConnect’ for signature ‘"function"’ 
>

**Comment by hadley** [comment]
Sorry I meant `RMySQL::MySQL()`

**Comment by LGTrader** [comment]
I don't think my skill set is high enough to be working on this. I added the () to call the function when connecting to the database, and there's no error messages there, but now I'm just back to the character message again when it tries to get the actual data. 

If I understood Joshua on the R list then I really need a newer Rmysql package and shouldn't have to edit my code (I was willing to edit for the purpose of testing only) but I'm not using Rmysql much right now and there's nothing newer in CRAN than what I already have installed, or Rstudio doesn't see it. Anyway, I don't want to jump into development packages so I'll let the OP get involved if he's still interested but will still try things in my code if they are straightforward. Please remember I'm not a developer, just an end-user flunkie.

Thanks

> if (UseMySQL){
+   if (MyAdjust) { dbName = paste0(dbName, "Adjust")}
+ #  dbc = dbConnect(MySQL(), dbname=dbName)
+   dbc = dbConnect(RMySQL::MySQL(), dbname=dbName)
+ #  setDefaults(getSymbols.MySQL, user="mark", password="MyTempPassword", dbname=dbName)
+ }

> for (i in 1:length(TestSym)){
+       print(paste("From MySQL -- ",TestSym[i]))
+ #      getSymbols(TestSym[i], src="MySQL")
+       getSymbols(TestSym[i], src="MySQL", user="mark", password="MyTempPassword", dbname=dbName)
+       assign(TestSym[i], get(TestSym[i])[paste0(DataStart,"/",DataEnd)])
+     }
[1] "From MySQL --  SPY"
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbConnect’ for signature ‘"character"’
>     dbDisconnect(dbc)
[1] TRUE
>

**Comment by joshuaulrich** [comment]
@LGTrader quantmod (getSymbols.R:L614) needs editing, not RMySQL.

**Comment by LGTrader** [comment]
OK, I don't even know where that is or how to rebuild it if I edited it:

c2RAID6 ~ # locate getSymbols.R
/home/mark/R/Demos/Quantstrat/luxor.getSymbols.R
/home/mark/R/x86_64-pc-linux-gnu-library/3.1/quantstrat/demo/luxor.getSymbols.R
/home/mark/blotter/pkg/quantstrat/demo/luxor.getSymbols.R
c2RAID6 ~ #

I'll leave it to you guys to work this out as at this point it would probably be easier for you to set up MySQL than me do these edits. If something shows up in CRAN so that Rstudio can grab it I will be very happy to test but this isn't for me. Sorry.

**Comment by LGTrader** [comment]
Unsubscribed from this thread
